name: Web-ext Lint, Build, Sign, and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created]

permissions:
  contents: write

jobs:
  check-commit:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - id: check
        run: |
          if git log -1 --pretty=%B | grep -q "Update dist folder"; then
            echo "should_run=false" >> $GITHUB_OUTPUT
          else
            echo "should_run=true" >> $GITHUB_OUTPUT
          fi

  lint:
    needs: check-commit
    if: needs.check-commit.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: '**/.github/workflows/*.yml'
    - name: Lint Chrome extension
      run: npx --yes web-ext lint --source-dir src/chrome
    - name: Lint Firefox extension
      run: npx --yes web-ext lint --source-dir src/firefox

  build:
    needs: [check-commit, lint]
    if: github.event_name == 'push' && needs.check-commit.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: '**/.github/workflows/*.yml'
    - name: Clear dist folder
      run: |
        rm -rf dist
        mkdir dist
    - name: Build Chrome extension
      run: npx --yes web-ext build --source-dir src/chrome --artifacts-dir dist --filename WWSIV_Amazon_Tagger_v{version}_chrome.zip --overwrite-dest
    - name: Build Firefox extension
      run: npx --yes web-ext build --source-dir src/firefox --artifacts-dir dist --filename WWSIV_Amazon_Tagger_v{version}_firefox.xpi --overwrite-dest
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add dist
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update dist folder"
          git push
        fi

  release:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: '**/.github/workflows/*.yml'
    - name: Get version
      id: get_version
      run: echo "VERSION=$(jq -r .version src/chrome/manifest.json)" >> $GITHUB_OUTPUT
    - name: Clear dist folder
      run: |
        rm -rf dist
        mkdir dist
    - name: Build Chrome extension
      run: npx --yes web-ext build --source-dir src/chrome --artifacts-dir dist --filename wwsiv_amazon_tagger_v${{ steps.get_version.outputs.VERSION }}_chrome.zip --overwrite-dest
    - name: Build Firefox extension
      run: npx --yes web-ext build --source-dir src/firefox --artifacts-dir dist --filename wwsiv_amazon_tagger_v${{ steps.get_version.outputs.VERSION }}_firefox.xpi --overwrite-dest
    - name: Sign Firefox extension
      env:
        WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
        WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
      run: |
        npx --yes web-ext sign --channel unlisted \
          --api-key "$WEB_EXT_API_KEY" \
          --api-secret "$WEB_EXT_API_SECRET" \
          --source-dir src/firefox \
          --artifacts-dir dist
    - name: Rename signed Firefox extension
      run: |
        signed_file=$(find dist -name "*.xpi" -not -name "wwsiv_amazon_tagger_v*" | head -n 1)
        if [ -n "$signed_file" ]; then
          mv "$signed_file" dist/wwsiv_amazon_tagger_v${{ steps.get_version.outputs.VERSION }}_firefox.xpi
          echo "Renamed signed extension to wwsiv_amazon_tagger_v${{ steps.get_version.outputs.VERSION }}_firefox.xpi"
        else
          echo "No signed Firefox extension found"
          exit 1
        fi
    - name: Upload Chrome Extension Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/wwsiv_amazon_tagger_v${{ steps.get_version.outputs.VERSION }}_chrome.zip
        asset_name: wwsiv_amazon_tagger_v${{ steps.get_version.outputs.VERSION }}_chrome.zip
        asset_content_type: application/zip
    - name: Upload Firefox Extension Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./dist/wwsiv_amazon_tagger_v${{ steps.get_version.outputs.VERSION }}_firefox.xpi
        asset_name: wwsiv_amazon_tagger_v${{ steps.get_version.outputs.VERSION }}_firefox.xpi
        asset_content_type: application/x-xpinstall
