name: Web-ext Lint, Build, and Sign

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  check-commit:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - id: check
        run: |
          if git log -1 --pretty=%B | grep -q "Update dist folder"; then
            echo "should_run=false" >> $GITHUB_OUTPUT
          else
            echo "should_run=true" >> $GITHUB_OUTPUT
          fi

  lint:
    needs: check-commit
    if: needs.check-commit.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: '**/.github/workflows/*.yml'
    - name: Lint Chrome extension
      run: npx --yes web-ext lint --source-dir src/chrome
    - name: Lint Firefox extension
      run: npx --yes web-ext lint --source-dir src/firefox

  build-sign-and-commit:
    needs: [check-commit, lint]
    if: github.event_name == 'push' && needs.check-commit.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: '**/.github/workflows/*.yml'
    - name: Build Chrome extension
      run: npx --yes web-ext build --source-dir src/chrome --artifacts-dir dist --filename WWSIV_Amazon_Tagger_v{version}_chrome.zip --overwrite-dest
    - name: Build Firefox extension
      run: npx --yes web-ext build --source-dir src/firefox --artifacts-dir dist --filename WWSIV_Amazon_Tagger_v{version}_firefox.xpi --overwrite-dest
    - name: Sign Firefox extension
      env:
        WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
        WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
      run: |
        npx --yes web-ext sign --channel unlisted \
          --api-key "$WEB_EXT_API_KEY" \
          --api-secret "$WEB_EXT_API_SECRET" \
          --approval-timeout \
          --source-dir src/firefox \
          --artifacts-dir dist
    - name: Rename signed Firefox extension
      run: |
        signed_file=$(find dist -name "*.xpi" -not -name "WWSIV_Amazon_Tagger_v*" | head -n 1)
        if [ -n "$signed_file" ]; then
          version=$(jq -r .version src/firefox/manifest.json)
          mv "$signed_file" "dist/WWSIV_Amazon_Tagger_v${version}_firefox_signed.xpi"
        else
          echo "No signed Firefox extension found"
          exit 1
        fi
    - name: Commit and push if changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add dist
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update dist folder"
          git push
        fi
